[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xattrs"
version = "0.1.0"
description = 'eXtensible serializing and deserializing tools for attrs'
readme = "README.md"
requires-python = ">=3.7"
license = "BSD-3-Clause"
keywords = ["attrs", "cattrs", "json", "serde"]
authors = [{ name = "Lanqing Huang", email = "lqhuang@outlook.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = ["attrs"]

[project.urls]
Documentation = "https://github.com/lqhuang/xattrs#readme"
Issues = "https://github.com/lqhuang/xattrs/issues"
Source = "https://github.com/lqhuang/xattrs"

## Build


## Formatter
[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

## Linter
[tool.ruff]
line-length = 88

# Enable rules:
# Pyflakes (F), pycodestyle (E, W), pydocstyle (D), pyupgrade (UP),
# flake8-bandit (S), flake8-bugbear (B), flake8-comprehensions (C4), flake8-datetimez (DTZ), flake8-pytest-style (PT)
# Pylint (PLC, PLE, PLR, PLW), Ruff-specific rules (RUF)
select = ["F", "E", "W", "UP", "S", "B", "C4", "DTZ", "PT"]
extend-select = ["PLC", "PLE", "PLR", "PLW", "RUF"]

ignore = [
  "E501",    # Line too long (95 > 88 characters)
  "S101",    # Use of `assert` detected
  "RUF100",  # Unused `noqa` directive for: E305 (not implemented)
  "PLR2004", # Magic value used in comparison, consider replacing with a constant variable
  "PLR0913", # Too many statements
  "C408",
  "B027",    # Allow non-abstract empty methods in abstract base classes
]

fix = false
#  A list of check code prefixes to consider autofix-able.
fixable = ["F", "E711", "UP", "B"]
unfixable = [
  "I",
  "F401", # Don't touch unused imports
]

ignore-init-module-imports = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"] # imported but unused
"tests/**/*" = [
  "PLR2004",
  "S101",
  "TID252",
] # Tests can use magic values, assertions, and relative imports

[tool.ruff.isort]

known-first-party = ["attrs_serde"]
known-third-party = ["attrs", "pytest", "typing_extensions"]
