# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  # push:
  #   branches: ["master"]
  #   paths-ignore:
  #     - "docs/**"
  #     - "*.md"
  #     - "*.rst"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.rst"
  workflow_dispatch:

env:
  FORCE_COLOR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

permissions:
  contents: read

jobs:
  tests:
    name: Tests on ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"

    continue-on-error: >-
      ${{ contains(matrix.python-version, 'dev') && true || false }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -Im pip install --upgrade pip
          python -Im pip install .[tests]
      - name: Test with pytest
        run: |
          pytest .

  mypy:
    name: Mypy on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: cache mypy
        uses: actions/cache@v4.0.0
        with:
          path: ./.mypy_cache
          key:
            mypy|${{ matrix.python-version }}|${{ hashFiles('pyproject.toml') }}
      - run: python -Im pip install --upgrade wheel tox
      - run: python -Im tox run -e mypy
